name: EAS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on EAS
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Setup EAS (expo action)
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: (Optional) EAS Update (OTA publish)
        if: env.ENABLE_EAS_UPDATE == 'true'
        working-directory: ./app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          # Ensure eas-cli is available
          npm install -g eas-cli
          # Use EXPO_TOKEN env var (do not call `eas login --token` in CI)
          eas whoami || true
          eas update --branch preview --message "CI: OTA update from $GITHUB_SHA" --non-interactive

      - name: Build on EAS (Android only)
        working-directory: ./app
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          # Ensure eas-cli is available
          npm install -g eas-cli
          # Use EXPO_TOKEN env var (do not call `eas login --token` in CI)
          eas whoami || true
          eas build --platform android --non-interactive --no-wait --profile preview